services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: nasa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre+123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
