import "reflect-metadata";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Providers } from "./providers";
import Nav from "./components/Navbar";
import {
  validateRequest,
  getUser,
} from "./auth/validate-request/validate-request";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AstrOn",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const result = await validateRequest();
  const user = await getUser(result.user?.id ?? "");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#021631" }}
      >
        <Providers>
          <Nav user={user} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
